spring:
  #Druid
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/keep_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: joe966

  #发送邮件
  mail:
    host: smtp.163.com #SMTP服务器地址
    username: joewong966@163.com #登陆账号
    password: joe966 #登陆密码（或授权码）
    properties:
      from: joewong966@163.com #邮件发信人（即真实邮箱）
    thymeleaf:
      cache: false
      prefix: classpath:/views/
    servlet:
      multipart:
        max-file-size: 10MB #限制单个文件大小
        max-request-size: 50MB #限制请求总量

#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## Mybatis
logging:
  level:
    com:
      jjy:
        aircinema:
          dao: debug
    org:
      springframework:
        web: trace

#token
token:
  expire-time: 86400000
  secret: riaperenohp
server:
  port: 8082
